call plug#begin('~/.vim/plugged')

Plug 'davidhalter/jedi-vim'

Plug 'morhetz/gruvbox'

Plug 'tlhr/anderson.vim'

Plug 'vim-airline/vim-airline-themes'

Plug 'fatih/vim-go'

Plug 'lervag/vimtex'

Plug 'maksimr/vim-jsbeautify'

Plug 'othree/html5.vim'

Plug 'pangloss/vim-javascript'

Plug 'christoomey/vim-tmux-navigator'

Plug 'rip-rip/clang_complete'

Plug 'ap/vim-css-color'

Plug 'c.vim'

Plug 'octol/vim-cpp-enhanced-highlight'

Plug 'https://github.com/Yggdroot/indentLine.git'

Plug 'https://github.com/scrooloose/nerdtree.git'

Plug 'https://github.com/scrooloose/syntastic.git'

Plug 'marijnh/tern_for_vim'

Plug 'chriskempson/base16-vim'

Plug 'vim-airline/vim-airline'

Plug 'Valloric/YouCompleteMe'

cal plug#end()

" Remap Leater
let mapleader = " "
" Add empty line bellow
nnoremap <leader>l o<Esc> 
" Add empty line above
nnoremap <leader>L O<Esc> 
" Change word with paste
nnoremap <leader>cp viwpyiw

" For windows
nnoremap <leader>wl <C-w>l
nnoremap <leader>wh <C-w>h
nnoremap <leader>wj <C-w>j
nnoremap <leader>wk <C-w>k
nnoremap <leader>w<Left> <C-w>h
nnoremap <leader>w<Right> <C-w>l
nnoremap <leader>w<Down> <C-w>j
nnoremap <leader>w<Up> <C-w>k
nnoremap <leader>wv <C-w>v
nnoremap <leader>wb <C-w>S
nnoremap <leader>wq :q<Enter>
nnoremap <leader>sq :wq<Enter>
nnoremap <leader>wrl :vertical resize +5<Enter>
nnoremap <leader>wrh :vertical resize -5<Enter>
nnoremap <leader>wr<Right> :vertical resize +5<Enter>
nnoremap <leader>wr<Left> :vertical resize -5<Enter>
nnoremap <leader>wml <C-w>L 
nnoremap <leader>wm<Right> <C-w>L
nnoremap <leader>ww :bnext<Enter>
" NERDTree
nnoremap <leader>nt :NERDTreeToggle<Enter>
let g:jedi#goto_command = "<leader>pg"
let g:jedi#goto_definitions_command = "<leader>pg"
let g:jedi#documentation_command = "pd"
let g:jedi#usages_command = "<leader>n"
let g:jedi#completions_command = "<C-Space>"
let g:jedi#rename_command = "<leader>pr"
let g:jedi#force_py_version = 3

"C++ clang-rename
noremap <leader>crr :pyf ~/Documents/Github/Config/vim/clang-rename.py<cr>

"GVIM
set guioptions-=m  "remove menubar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hand scroll bar
set guicursor+=n-v-c:blinkon0
set guifont=Source\ Code\ Pro\ 10
" Set good line number
set nu
set relativenumber

"syntax enable
let base16colorspace=256
set t_Co=256

" Color scheme
colorscheme gruvbox
"let g:gruvbox_contrast_dark='hard'
set background=dark  

"let g:airline#extensions#tabline#enabled=1
"#let g:airline1extensionstabline#left_sep = ' '
"let g:airline1extensionstabline#left_alt_sep = '|'
"set laststatus=2



set tabstop=4 shiftwidth=4 expandtab
set clipboard=unnamed,unnamedplus

set nowrap

"set changing mode fast
set ttimeoutlen=0

" for command mode
nnoremap <S-Tab> <<

" for insert mode
nnoremap <S-Tab> <C-d>

" colorize cusor for marching parenthesiss
hi MatchParen cterm=none ctermbg=green ctermfg=blue

" Golang go
let g:syntastic_go_checkers = ['go']

" vimwiki
set nocompatible
filetype plugin on
syntax on
"let g:vimwiki_list = [{'auto_export': 1}]

" Global Clipboard
py << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF

let &t_SI = "\<Esc>]12;orange\x7"
let &t_SR = "\<Esc>]12;white\x7"
let &t_EI = "\<Esc>]12;white\x7"

" Default setting for syntastic 
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

" Default setting for syntastic 
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
