#
# ~/.bashrc
#

# If not running interactively, don't do anything

# All new Path

#PATH=~/Documents/Programs/nodejs/bin:$PATH
#PATH=~/Documents/Programs/anaconda3/bin:$PATH
PATH=~/go/bin/gocode:$PATH
export GOPATH=~/go
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk/jre/
export TERM=xterm-256color
export CC=/usr/bin/gcc-5
export CXX=/usr/bin/g++

# Color theme for termina
source "/home/nathaniel/Documents/Programs/terminal/base16-shell/scripts/base16-brewer.sh"
zsh
